name: DKits
author: DevilGamer_ | BrunoDEV | Kits Edit
description: Plugin de KitPvP
main: me.dkits.Main
version: 1.0
commands:
  build:
  kits:
  kit:
  specialist:
  status:
  pvp:
  kit:
  archer:
  bazooka:
  knock:
  main:
  mlg:
  head:
  kangaroo:
  andromeda:
  magma:
  camel:
  reaper:
  accumulator:
  sonic:
  lag:
  turbo:
  togglepvp:
  deshfire:
  skit:
  neo:
  challenge:
  att:
  kyuubi:
  setchallenge:
  launcher:
  clear:
  troll:
  sayajin:
  scorpion:
  hunter:
  weakhand:
  invsee:
  deshfire:
  darkgod:
  loja:
  ryu:
  achilles:
  warps:
  sharingan:
  infected:
  gladiator:
  npcsopa:
  wolverine:
  sumo:
  shop:
  1v1:
  salamander:
  hulk:
  frosty:
  vacuum:
  resouper:
  skeleton:
  grappler:
  fps:
  rdm:
  main:
  earlyhg:
  monk:
  viper:
  camel:
  forcefield:
  urgal:
  switcher:
  milkman:
  barbarian:
  stoneman:
  avatar:
  turtle:
  sniper:
  viking:
  dkits:
  clear:
  pulapula:
  paladino:
  ninja:
  resetkit:
  fly:
  dia:
  noite:
  suicide:
  anchor:
  flash:
  fireman:
  grandpa:
  fujao:
  critical:
  fisherman:
  stomper:
  snail:
  poseidon:
  naruto:
  confuser:
  avatar:
  doctor:
  morf:
  warp:
  warps:
  lfacil:
  lmedio:
  lextreme:
  ldificil:
  setchallenger:
  setfps:
  setmain:
  setknock:
  setmlg:
  setspawn:
  spawn:
  glider:
  fps:
  alert:
  npcsopa:
  tag:
  bc:
  broadcast:
  troll:
  report:
  endermage:
  challenge:
  challenger: